name: Lint and Test Charts

on: pull_request

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Lint the  chart
        id: lint
        uses: helm/chart-testing-action@v1.0.0
        with:
          command: lint --all

      - name: Create kind cluster
        uses: helm/kind-action@v1.0.0

      - name: Install the chart
        uses: helm/chart-testing-action@v1.0.0
        with:
          command: install --all
